name: ros build

on:
  push:
    branches: [ melodic-devel ]
  pull_request:
    branches: [ melodic-devel ]


jobs:
  call-ros-ci-build-melodic:
    uses: LCAS/rosdistro/.github/workflows/_lcas_ci_build.yaml@master
    with:
      packages: mqtt_bridge
      ros_distribution: melodic
      docker_image: ubuntu:bionic
      ros_version: 1
